
import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useDropzone } from "react-dropzone";
import { Minimize2, Maximize2, X } from "lucide-react";
import { api } from "../utils/api";
import { RichTextEditor } from "./editor/RichTextEditor";
import { AttachmentList, type Attachment } from "./compose/AttachmentList";
import { useModalAccessibility } from "../hooks/useModalAccessibility";
import {
    type ComposeModalProps,
    RecipientsSection,
    SubjectInput,
    ModalFooter
} from "./compose-modal-modules";

export function ComposeModal({ token, inboxes, onClose, initialSubject = "", initialBody = "", initialTo = "", initialFrom = "" }: ComposeModalProps) {
    const [isMinimized, setIsMinimized] = useState(false);
    const [composeFrom, setComposeFrom] = useState(initialFrom);
    const [composeTo, setComposeTo] = useState(initialTo);
    const [composeCc, setComposeCc] = useState("");
    const [composeBcc, setComposeBcc] = useState("");
    const [showCcBcc, setShowCcBcc] = useState(false);
    const [composeSubject, setComposeSubject] = useState(initialSubject);
    const [composeHtml, setComposeHtml] = useState(initialBody);
    const [attachments, setAttachments] = useState<Attachment[]>([]);
    const [busy, setBusy] = useState(false);
    const [error, setError] = useState("");

    const { modalRef, modalProps } = useModalAccessibility({
        isOpen: !isMinimized,
        onClose: () => {
            if (!busy) onClose();
        },
        closeOnEsc: !busy,
    });

    const onDrop = useCallback((acceptedFiles: File[]) => {
        const newAttachments = acceptedFiles.map(file => ({
            id: crypto.randomUUID(),
            file,
            uploading: false
        }));
        setAttachments(prev => [...prev, ...newAttachments]);
    }, []);

    const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop, noClick: true });

    const handleRemoveAttachment = (id: string) => {
        setAttachments(prev => prev.filter(att => att.id !== id));
    };

    const handleCompose = async () => {
        if (!composeFrom || !composeTo || !composeSubject) return;
        setBusy(true);
        setError("");
        try {
            const formData = new FormData();
            formData.append("from", composeFrom);
            formData.append("to", composeTo);
            if (composeCc) formData.append("cc", composeCc);
            if (composeBcc) formData.append("bcc", composeBcc);
            formData.append("subject", composeSubject);

            // Send HTML content. Text version can be generated by backend or stripped here.
            formData.append("html", composeHtml);

            // Simple text fallback (stripping tags)
            const div = document.createElement("div");
            div.innerHTML = composeHtml;
            const text = div.textContent || div.innerText || "";
            formData.append("text", text);

            attachments.forEach(att => {
                formData.append("attachments", att.file);
            });

            await api("/messages/outbound", {
                method: "POST",
                token,
                body: formData,
            });
            onClose();
        } catch (err) {
            setError((err as Error).message);
        } finally {
            setBusy(false);
        }
    };

    const canSend = !!(composeFrom && composeTo && composeSubject) && !busy;

    const toggleMinimize = () => setIsMinimized(!isMinimized);

    const containerClasses = isMinimized
        ? "fixed bottom-0 right-4 z-50 w-72 bg-white dark:bg-gray-900 rounded-t-lg shadow-xl border border-gray-200 dark:border-gray-700 overflow-hidden"
        : "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4";

    const modalClasses = isMinimized
        ? "w-full h-full flex flex-col"
        : "glass-card-elevated w-full max-w-4xl h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-[var(--nebula-border)] bg-white dark:bg-gray-900";

    if (isMinimized) {
        return (
            <div className={containerClasses}>
                <div
                    className="flex items-center justify-between p-3 bg-gray-100 dark:bg-gray-800 cursor-pointer border-b border-gray-200 dark:border-gray-700"
                    onClick={() => setIsMinimized(false)}
                >
                    <span className="font-medium truncate text-sm text-gray-700 dark:text-gray-200">
                        {composeSubject || "New Message"}
                    </span>
                    <div className="flex items-center space-x-2">
                        <button
                            onClick={(e) => { e.stopPropagation(); setIsMinimized(false); }}
                            className="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded"
                        >
                            <Maximize2 size={14} className="text-gray-500" />
                        </button>
                        <button
                            onClick={(e) => { e.stopPropagation(); onClose(); }}
                            className="p-1 hover:bg-gray-200 dark:hover:bg-gray-700 rounded"
                        >
                            <X size={14} className="text-gray-500" />
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className={containerClasses}
                onClick={onClose}
            >
                <motion.div
                    ref={modalRef}
                    {...modalProps}
                    aria-labelledby="compose-modal-title"
                    initial={{ opacity: 0, scale: 0.95, y: 20 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 20 }}
                    transition={{ type: "spring", duration: 0.5, bounce: 0.3 }}
                    className={modalClasses}
                    onClick={(e) => e.stopPropagation()}
                >
                    {/* Dropzone wrapper - separate from motion.div to avoid type conflicts */}
                    <div {...getRootProps()} className="contents">
                    {/* Header */}
                    <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--nebula-border)] bg-[var(--nebula-surface)]/50 backdrop-blur-md">
                        <h2 id="compose-modal-title" className="text-lg font-semibold text-[var(--nebula-text-primary)]">
                            Compose Email
                        </h2>
                        <div className="flex items-center space-x-2">
                            <button
                                onClick={toggleMinimize}
                                className="p-2 hover:bg-black/5 dark:hover:bg-white/5 rounded-full transition-colors"
                                title="Minimize"
                            >
                                <Minimize2 size={18} className="text-[var(--nebula-text-secondary)]" />
                            </button>
                            <button
                                onClick={onClose}
                                className="p-2 hover:bg-red-500/10 hover:text-red-500 rounded-full transition-colors"
                                title="Close"
                            >
                                <X size={18} className="text-[var(--nebula-text-secondary)]" />
                            </button>
                        </div>
                    </div>

                    {error && (
                        <div className="px-6 pt-4">
                            <div className="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 p-3 rounded-md text-sm">
                                {error}
                            </div>
                        </div>
                    )}

                    {/* Body */}
                    <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-[var(--nebula-surface)]/20 relative">
                        {isDragActive && (
                            <div className="absolute inset-0 z-10 bg-blue-500/10 backdrop-blur-sm flex items-center justify-center border-2 border-blue-500 border-dashed m-4 rounded-xl">
                                <p className="text-blue-600 font-medium text-lg">Drop files to attach</p>
                            </div>
                        )}

                        <input {...getInputProps()} />

                        <RecipientsSection
                            inboxes={inboxes}
                            composeFrom={composeFrom}
                            setComposeFrom={setComposeFrom}
                            composeTo={composeTo}
                            setComposeTo={setComposeTo}
                            composeCc={composeCc}
                            setComposeCc={setComposeCc}
                            composeBcc={composeBcc}
                            setComposeBcc={setComposeBcc}
                            showCcBcc={showCcBcc}
                            setShowCcBcc={setShowCcBcc}
                        />

                        <SubjectInput value={composeSubject} onChange={setComposeSubject} />

                        <div className="space-y-2 flex flex-col flex-1 min-h-[350px]">
                            <label className="text-[11px] font-bold text-[var(--nebula-text-muted)] uppercase tracking-widest ml-1 flex items-center gap-2">
                                Message
                            </label>
                            <RichTextEditor
                                content={composeHtml}
                                onChange={setComposeHtml}
                                className="flex-1 min-h-[300px]"
                                placeholder="Write your message here..."
                            />
                        </div>

                        <AttachmentList attachments={attachments} onRemove={handleRemoveAttachment} />
                    </div>
                    </div>

                    <ModalFooter
                        busy={busy}
                        canSend={canSend}
                        onClose={onClose}
                        onSend={handleCompose}
                    />
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}
