// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const ErrorBoundary: typeof import('D:/project/Clone/email-platform/services/extension/src/components/ErrorBoundary')['default']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const announceToScreenReader: typeof import('D:/project/Clone/email-platform/services/extension/src/utils/accessibility')['announceToScreenReader']
  const browser: typeof import('wxt/browser')['browser']
  const cn: typeof import('D:/project/Clone/email-platform/services/extension/src/utils/cn')['cn']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useCompose: typeof import('D:/project/Clone/email-platform/services/extension/src/hooks/useCompose')['useCompose']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useFocusTrap: typeof import('D:/project/Clone/email-platform/services/extension/src/utils/accessibility')['useFocusTrap']
  const useGlobalSearch: typeof import('D:/project/Clone/email-platform/services/extension/src/hooks/useGlobalSearch')['useGlobalSearch']
  const useListNavigation: typeof import('D:/project/Clone/email-platform/services/extension/src/utils/accessibility')['useListNavigation']
  const useMemo: typeof import('react')['useMemo']
  const useOtpWatcher: typeof import('D:/project/Clone/email-platform/services/extension/src/hooks/useOtpWatcher')['useOtpWatcher']
  const usePinnedInboxes: typeof import('D:/project/Clone/email-platform/services/extension/src/hooks/usePinnedInboxes')['usePinnedInboxes']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ErrorBoundary } from 'D:/project/Clone/email-platform/services/extension/src/components/ErrorBoundary'
  import('D:/project/Clone/email-platform/services/extension/src/components/ErrorBoundary')
}
